name: FE Create Release PR
on:
  push:
    branches:
      - test
jobs:
  create-release-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.push.head.ref }}
          repository: ${{ github.event.push.head.repo.full_name }}
      - name: Get PR title and author
        id: pr_info
        run:  echo "${{ toJson(github.event) }}"
  