name: FE Release
on:
  push:
    branches:
      - test
jobs:
  create-release-PR:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[Bot Release]') == false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install
      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      # !!!open Workflow permissions setting, Actions -> general -> Workflow permissions -> Read and write permissions
      # When releasing, a commit will be created and then submitted to the branch, creating a PR to merge with the protected branch
      - name: Create Publishing to NPM and GitHub PR
        run: npm run release:create
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, '[Bot Release]') == true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install
      - name: Config Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      # !!!open Workflow permissions setting, Actions -> general -> Workflow permissions -> Read and write permissions
      # When releasing, a commit will be created and then submitted to the branch, creating a PR to merge with the protected branch
      - name: Publishing to NPM and GitHub
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
